### ISSUE TITLE
csladspa cannot open corrsponding csd-files

### ISSUE THREAD

**Issue by genell** [csound/csladspa#2]
After cloning csladspa repos and building csladspa, testing fails with the included example CSOUNDladspa csd files, giving the message:
attempting to load plugin index: 0
PLUGIN NOT LOADED: probably missing csLADSPA section
no more csLADSPA plugins

$ echo $LADSPA_PATH
/usr/lib/ladspa

$ ls -1 /usr/lib/ladspa/
[snip]
csladspa64.so
CSOUNDladspaGain.csd
[snip]

$ analyseplugin csladspa64
attempting to load plugin index: 0
PLUGIN NOT LOADED: probably missing csLADSPA section
no more csLADSPA plugins

$ uname -r
5.9.0-4-amd64

**Comment by vlazzarini** [comment]
Not quite sure what's going on, but I just tested it here on MacOS using Audacity and I can get the effect to run. 

```
<csLADSPA>
Name=Csound-FLANGER
Maker=Victor Lazzarini
UniqueID=1054
Copyright=None
ControlPort=Flange Depth|depth
Range=0|1
ControlPort=Flange Rate|rate
Range=0|10
</csLADSPA>
	

<CsoundSynthesizer>
	
<CsInstruments>
	
sr = 44100
ksmps = 10
nchnls = 1

instr 1
	
kdeltime    chnget "depth"
krate       chnget "rate"
	
ain         in

	
a1          oscil kdeltime, 1, 1
	
ar          vdelay3 ain, a1+kdeltime, 1000
	
            out ar+ain

endin
	
</CsInstruments>
	
<CsScore>
	
f1 0 1024 10 1
i1 0 3600
	
</CsScore>

</CsoundSynthesizer>
```

**Comment by genell** [comment]
I have tried on a few different linux machines, and I also tried an old version provided by ubuntu 16.04 repos (csladspa 1:6.05~dfsg1-7build1) with the same results. 
Perhaps someone who, unlike me, actually knows what they're doing could try it on a linux machine?
Or could I run it in some kind of debugger?

**Comment by rorywalsh** [comment]
I just built this in Ubuntu 18.04. I see no issues. This is the output from analyseplugin:

```
rory@rory-MS-7B17:~/.ladspa$ analyseplugin csladspa64.so 
attempting to load plugin index: 0
cSLADSPA plugin found: 
<csLADSPA>
Name=CsoundGain Plugin
Maker=Victor Lazzarini
UniqueID=1049
Copyright=None
ControlPort=Gain|gain
ControlPort=Test|test
</csLADSPA>
PLUGIN LOADED

Plugin Name: "CsoundGain Plugin"
Plugin Label: "/home/rory/.ladspa/gain.csd"
Plugin Unique ID: 1049
Maker: "Victor Lazzarini     (csLADSPA64: Lazzarini, Walsh)"
Copyright: "None"
Must Run Real-Time: No
Has activate() Function: No
Has deactivate() Function: No
Has run_adding() Function: No
Environment: Normal or Hard Real-Time
Ports:  "csladspa-audio-in0" input, audio
        "csladspa-audio-out0" output, audio
        "Gain" input, control, 0 to 2
        "Test" input, control, 0 to 2
no more csLADSPA plugins
```

**Comment by vlazzarini** [comment]
I wonder if the issue is to do with permissions?

**Comment by genell** [comment]
Hm. Quite possibly. 
If I run 
sudo analyseplugin /usr/lib/ladspa/csladspa64.so
it works as expected if I run it from a folder where I have a csladspa-compatible csd-file.
If the csd-file is in the system LADSPA_PATH (/usr/lib/ladspa/) there is no error 
This makes me suspect I have not understood how csladspa is supposed to work.

So, what permissins should I have, and where should I ideally put the corresponding csd-file?
Is there perhaps a group I should be member of but that I am not?

**Comment by rorywalsh** [comment]
I think that's the issue. The .csd files have to reside in the same folder as the csladspa64.so library.  If not the csladspa lib won't be able to find them.

**Comment by genell** [comment]
Well, for my very first test they were in the same folder, namely /usr/lib/ladspa/ 
When running analyseplugin, the files seem to be found (because it tries to load them) but there seems to be a permissions issue.
When having the files (both the csladspa64.so and the csd) in /usr/bin/ladspa and running analyseplugin under sudo, no csd is found. 
When having a csd in my current folder (say e.g. /home/anders) but the csladspa64.so in /usr/lib/ladspa, the csd is found and is loaded.
EDIT: That last bit is when running as sudo. When I run with normal privileges I get my original error.

**Comment by genell** [comment]
I tested again now on a different machine, and if I run 
analyseplugin /home/anders/Src/csladspa/build/csladspa64.so 
with one of the example plugins in the same folder things work as expected without elevated permissions.
I think this ticket can be closed - sorry for the noise.

**Comment by zonkmachine** [comment]
I'm on Ubuntu 20.10. I have found no way to make csladspa work in the default installation from the repository. I need to copy csladspa64.so to my $HOME and work from there. I try to use csladspa in LMMS.

```
$ echo $LADSPA_PATH
/usr/lib/ladspa
```

```
$ ls /usr/lib/ladspa/
...
csladspa64.so
CSOUNDladspaGain.csd
...
```


```
$ analyseplugin /usr/lib/ladspa/csladspa64.so 
attempting to load plugin index: 0
PLUGIN NOT LOADED: probably missing csLADSPA section
no more csLADSPA plugins
```

**Comment by genell** [comment]
You are right. Maybe this should be reopened until this is properly investigated?

So: 

It seems there is a combined permissions and path issue.

I can get things to work by setting LADSPA_PATH to a local folder such as /home/genell/csladspa and place both csladspa64.so and the corresponding csd there.

Without setting LADSPA_PATH i have to issue analyseplugin from the folder containing the csd-file, so
/home/genell~$ analyseplugin /home/genell/csladspa/csladspa64.so
works if the csd-file is in /home/genell, but not if it is /home/genell/csladspa/csladspa64.so
i.e. it looks for the csd-file in the current folder, not in the folder where csladspa64.so resides.
Likewise I can run
/home/genell~$ analyseplugin /usr/lib/ladspa/csladspa64.so
and without LADSPA_PATH set it works if I have the csd-file in the current folder.

I cannot without raised permissions get it to work if I place csladspa64.so and the corresponding csd in the ordinary ladspa folder /usr/lib/ladspa
I can call csladspa64.so using e.g. analyseplugin, but the ladspa process does not have permissions to read the csd-file in the /usr/lib/ladspa folder. I have tried to change permissions/ownership of the csd file in /usr/lib/ladspa to be accessible by 'all' but that does not help the issue.

Since access to csladspa64.so works through e.g. analyseplugin without raised permissions, would there also be a way to make the process access the csd in /usr/lib/ladspa without raising permissions?
